# Pre-commit TDD Hooks for AgenticSeek
# ===================================
# Ensures TDD compliance before commits

repos:
  # TDD Compliance Validation
  - repo: local
    hooks:
      - id: tdd-test-validation
        name: TDD Test Validation
        entry: python scripts/tdd_test_runner.py
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
        
      - id: tdd-comment-validation
        name: TDD Comment Block Validation
        entry: python scripts/validate_tdd_comments.py
        language: system
        files: '^sources/.*\.py$'
        stages: [commit]
        
      - id: test-coverage-check
        name: Test Coverage Threshold Check
        entry: python scripts/test_coverage_validator.py
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]

  # Code Quality Hooks
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [--line-length=100]
        
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=100, --ignore=E203,W503]

  # Additional Validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
EOF < /dev/null